server:
  port: 8090
spring:
  reactor:
    context-propagation: auto
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    registerWithEureka: true  # Ensures API Gateway registers itself
#    fetchRegistry: true  # Allows API Gateway to discover other services

management:
  server:
    port: 8443
    ssl:
      enabled: true
      key-store: classpath:gateway-keystore.p12
      key-store-password: gateway
      key-store-type: PKCS12
      key-alias: gateway
  endpoints:
    web:
      base-path: /api-gateway
      exposure:
        include: "*"

  tracing:
    propagation:
      consume: [ b3, w3c ]
      produce: [ b3 ]
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
