management:
  server:
    port: 8443
    ssl:
      enabled: true
      key-store: classpath:gateway-keystore.p12
      key-store-password: gateway
      key-store-type: PKCS12
      key-alias: gateway
  endpoints:
    web:
      base-path: /api-gateway
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
