server:
  port: 8761  # Default Eureka port

eureka:
  client:
    registerWithEureka: false  # No need for Eureka itself to register
    fetchRegistry: false
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
  server:
    renewal-percent-threshold: 0.49
