server:
  port: 8092
spring:
  application:
    name: uam-service
  mvc:
    servlet:
      path: /uam  # This sets the global prefix for all controllers
    pathmatch:
      matching-strategy: ant_path_matcher  # Ensures correct path mapping
  datasource:
    url: jdbc:mysql://localhost:3307/user_auth_db
    username: root
#    password: Sky_Dev#*75
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true

logging:
  level:
    root: INFO
    com.poc.microservices: DEBUG
    org.springframework.web: WARN

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

jwt:
#  secretKey: ENV var SECRET_KEY
  expirationMinutes: 60

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    preferIpAddress: true
#    leaseRenewalIntervalInSeconds: 30  # Ensures regular heartbeat updates
#    leaseExpirationDurationInSeconds: 90  # Prevents premature instance removal
