grpc:
  server:
    port: 9093
server:
  port: 8093
spring:
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: em-service
  mvc:
    servlet:
      path: /em  # This sets the global prefix for all controllers
    pathmatch:
      matching-strategy: ant_path_matcher  # Ensures correct path mapping
  datasource:
    url: jdbc:mysql://localhost:3307/employer_db
    username: root
#    password: Sky_Dev#*75
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true

#logging:
#  level:
#    root: INFO
#    com.poc.microservices: DEBUG
#    org.springframework.web: WARN
#
#eureka:
#  client:
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    preferIpAddress: true
#    leaseRenewalIntervalInSeconds: 30  # Ensures regular heartbeat updates
#    leaseExpirationDurationInSeconds: 90  # Prevents premature instance removal

resilience4j:
  circuitbreaker:
    instances:
      eemCircuitBreaker:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 3
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 5
