server:
  port: 8091
spring:
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    openfeign:
      okhttp:
        enabled: true
  application:
    name: mas-service
  mvc:
    servlet:
      path: /mas  # This sets the global prefix for all controllers
    pathmatch:
      matching-strategy: ant_path_matcher  # Ensures correct path mapping

security:
  excludedEndpoints: "/mas/mas-users/login,/mas/mas-users/register"

em:
  graphql:
    url: http://localhost:8093/em/graphql

#jwt:
  #  secretKey: ENV var SECRET_KEY

#logging:
#  level:
#    root: INFO
#    com.poc.microservices: DEBUG
#    org.springframework.web: WARN
#
#eureka:
#  client:
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    preferIpAddress: true
#    leaseRenewalIntervalInSeconds: 30  # Ensures regular heartbeat updates
#    leaseExpirationDurationInSeconds: 90  # Prevents premature instance removal
