server:
  port: 8091
spring:
  application:
    name: mas-service

logging:
  level:
    root: INFO
    com.poc.microservices: DEBUG
    org.springframework.web: WARN

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true