server:
  port: 8091
spring:
  config:
    import: optional:configserver:configserver
  cloud:
    openfeign:
      okhttp:
        enabled: true
  application:
    name: mas-service
  mvc:
    servlet:
      path: /mas  # This sets the global prefix for all controllers
    pathmatch:
      matching-strategy: ant_path_matcher  # Ensures correct path mapping

security:
  excludedEndpoints: "/mas/mas-users/login,/mas/mas-users/register"

em:
  graphql:
    url: http://localhost:8093/em/graphql
    service: http://api-gateway/em-service/em/graphql

management:
  tracing:
    propagation:
      consume: [ b3, w3c ]
      produce: [ b3 ]
      type: b3
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
